name: Create Release

on:
  pull_request:
    types: [closed]
    branches: [main, master]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build application
      run: ./gradlew build -x test
    
    - name: Get current version
      id: get_version
      run: |
        VERSION=$(grep "version = " build.gradle | cut -d "'" -f 2 | sed 's/-SNAPSHOT//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Generate tag name
      id: generate_tag
      run: |
        BASE_VERSION=${{ steps.get_version.outputs.version }}
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        TAG_NAME="v${BASE_VERSION}-${TIMESTAMP}"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
    
    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.generate_tag.outputs.tag_name }}
        git push origin ${{ steps.generate_tag.outputs.tag_name }}
    
    - name: Generate release notes
      id: release_notes
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        
        cat << EOF > release_notes.md
        ## Release ${{ steps.generate_tag.outputs.tag_name }}
        
        ### Changes
        **${PR_TITLE}** (#${PR_NUMBER})
        
        ${PR_BODY}
        
        ### Contributors
        - @${PR_AUTHOR}
        
        ### Build Information
        - Java Version: 17
        - Spring Boot Version: 3.4.4
        - Build Date: $(date '+%Y-%m-%d %H:%M:%S UTC')
        
        This release was automatically generated from pull request #${PR_NUMBER}
        EOF
        
        echo "notes_file=release_notes.md" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.generate_tag.outputs.tag_name }}
        name: Release ${{ steps.generate_tag.outputs.tag_name }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}